Only use the targeting pack nuget packages on non-windows (#7293)
Ideally we would use the .NET framework targeting pack references
everywhere but right now we are hitting error:

: error MSB3245: Could not resolve this reference. Could not locate the assembly "System.Runtime". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

github issue https://github.com/dotnet/core-sdk/issues/2455