INCOMPLETE: retire int block size; introduce long
Regenerated with new swagger to present block size on a GetBlocks call
as long instead of int, while preserving backwards compatibility.
Currently build error CS0282 due to a mix of generated and handwritten
properties.