Fix getblocks long (#19078)
* INCOMPLETE: retire int block size; introduce long

Regenerated with new swagger to present block size on a GetBlocks call
as long instead of int, while preserving backwards compatibility.
Currently build error CS0282 due to a mix of generated and handwritten
properties.

* Updated autorest swagger pointer

* Fixed build error

Moved all BlobBlock properties into handwritten partial file to avoid
compile error CS0282.

* Ignore multi GB test

* ModelFactory support

* export api

* Fix codegen url

* Handled overflow bug

* disabled long test due to timeout

* fixed broken url; regenerated

* Changelog

Co-authored-by: jschrepp-MSFT <41338290+jschrepp-MSFT@users.noreply.github.com>